# -*- coding: utf-8 -*-
"""Fungsi PCA_G.211.25.0067.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gJIGaJPYtqrHweSPDckDJyJv_bE6zL8i
"""

from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
import numpy as np

X_dummy = np.random.rand(5, 3)

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X_dummy)

pca = PCA(n_components=2)
X_projected = pca.fit_transform(X_scaled)

print("Hasil PCA dengan Scikit-Learn:")
print(X_projected)
print("\nVarians yang dijelaskan per komponen:", pca.explained_variance_ratio_)