# -*- coding: utf-8 -*-
"""Praktik 3 Muhammad Fadil Juan Pamungkas_G.211.25.0067.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19aVbfW1gsdn58AlVfQlAFC_aBgJQTxAN

Pseudocode (Algoritma Dijkstra)
"""

PROSEDUR Dijkstra(Graf, Simpul_Awal):
    Buat tabel Jarak dan isi semua simpul dengan Tak Terhingga (∞)
    Set Jarak[Simpul_Awal] = 0

    Buat Priority Queue (PQ)
    Masukkan (0, Simpul_Awal) ke dalam PQ

    SELAMA PQ tidak kosong:
        Ambil (dist, u) dengan dist terkecil dari PQ

        JIKA dist > Jarak[u]: Lanjutkan ke iterasi berikutnya

        UNTUK SETIAP tetangga v dari u dengan bobot w:
            Jarak_Baru = Jarak[u] + w

            JIKA Jarak_Baru < Jarak[v]:
                Jarak[v] = Jarak_Baru
                Masukkan (Jarak_Baru, v) ke dalam PQ

    KEMBALIKAN tabel Jarak

"""Coding"""

import heapq

def dijkstra(graph, start):
    distances = {node: float('infinity') for node in graph}
    distances[start] = 0

    priority_queue = [(0, start)]

    while priority_queue:
        current_distance, current_node = heapq.heappop(priority_queue)

        if current_distance > distances[current_node]:
            continue

        for neighbor, weight in graph[current_node].items():
            distance = current_distance + weight

            if distance < distances[neighbor]:
                distances[neighbor] = distance
                heapq.heappush(priority_queue, (distance, neighbor))

    return distances

graph_data = {
    'A': {'B': 4, 'C': 2},
    'B': {'A': 4, 'C': 5, 'D': 10},
    'C': {'A': 2, 'B': 5, 'D': 3},
    'D': {'B': 10, 'C': 3}
}

hasil = dijkstra(graph_data, 'A')
print(f"Jarak terpendek dari A: {hasil}")

"""Analisa Kompleksitas Waktu

Analisis ini sangat bergantung pada struktur data yang digunakan untuk menyimpan graf dan Priority Queue. Misalkan $V$ adalah jumlah simpul (Vertex) dan $E$ adalah jumlah sisi (Edge).Menggunakan Binary Heap (seperti kode di atas):Operasi Utama:Extract Min: Mengambil simpul dengan jarak terkecil dilakukan sebanyak $V$ kali. Setiap operasi memakan waktu $O(\log V)$.Decrease Key: Memperbarui jarak tetangga dilakukan sebanyak $E$ kali. Dalam implementasi heap, ini memakan waktu $O(\log V)$.Total Kompleksitas:$$O((V + E) \log V)$$Pada graf yang terhubung padat di mana $E > V$, ini sering disederhanakan menjadi $O(E \log V)$.
"""