# -*- coding: utf-8 -*-
"""praktik2_muhammad fadil juan pamungkas_g.211.25.0067.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10kIC1KUDf9Quelxvn0MnMMoscTg73GTC
"""

PROCEDURE RB-Insert-Fixup(T, z)
    WHILE z.parent.color == RED
        IF z.parent == z.parent.parent.left
            y = z.parent.parent.right (paman z)
            IF y.color == RED
                // Kasus 1: Paman merah, cukup recoloring
                z.parent.color = BLACK
                y.color = BLACK
                z.parent.parent.color = RED
                z = z.parent.parent
            ELSE
                IF z == z.parent.right
                    // Kasus 2: Paman hitam, z di kanan (Zig-Zag)
                    z = z.parent
                    LEFT-ROTATE(T, z)
                // Kasus 3: Paman hitam, z di kiri (Line)
                z.parent.color = BLACK
                z.parent.parent.color = RED
                RIGHT-ROTATE(T, z.parent.parent)
        ELSE (simetris untuk z.parent di sebelah kanan)
    T.root.color = BLACK

class Node:
    def __init__(self, data, color="RED"):
        self.data = data
        self.color = color
        self.left = None
        self.right = None
        self.parent = None

class RedBlackTree:
    def __init__(self):
        self.NIL = Node(0, color="BLACK")
        self.root = self.NIL

    def left_rotate(self, x):
        y = x.right
        x.right = y.left
        if y.left != self.NIL:
            y.left.parent = x
        y.parent = x.parent
        if x.parent == None:
            self.root = y
        elif x == x.parent.left:
            x.parent.left = y
        else:
            x.parent.right = y
        y.left = x
        x.parent = y

    def right_rotate(self, y):
        x = y.left
        y.left = x.right
        if x.right != self.NIL:
            x.right.parent = y
        x.parent = y.parent
        if y.parent == None:
            self.root = x
        elif y == y.parent.right:
            y.parent.right = x
        else:
            y.parent.left = x
        x.right = y
        y.parent = x

    def insert(self, key):
        node = Node(key)
        node.left = self.NIL
        node.right = self.NIL

        y = None
        x = self.root

        while x != self.NIL:
            y = x
            if node.data < x.data:
                x = x.left
            else:
                x = x.right

        node.parent = y
        if y == None:
            self.root = node
        elif node.data < y.data:
            y.left = node
        else:
            y.right = node

        if node.parent == None:
            node.color = "BLACK"
            return

        if node.parent.parent == None:
            return

        self.fix_insert(node)

    def fix_insert(self, k):
        while k.parent.color == "RED":
            if k.parent == k.parent.parent.right:
                u = k.parent.parent.left
                if u.color == "RED":
                    u.color = "BLACK"
                    k.parent.color = "BLACK"
                    k.parent.parent.color = "RED"
                    k = k.parent.parent
                else:
                    if k == k.parent.left:
                        k = k.parent
                        self.right_rotate(k)
                    k.parent.color = "BLACK"
                    k.parent.parent.color = "RED"
                    self.left_rotate(k.parent.parent)
            else:
                u = k.parent.parent.right
                if u.color == "RED":
                    u.color = "BLACK"
                    k.parent.color = "BLACK"
                    k.parent.parent.color = "RED"
                    k = k.parent.parent
                else:
                    if k == k.parent.right:
                        k = k.parent
                        self.left_rotate(k)
                    k.parent.color = "BLACK"
                    k.parent.parent.color = "RED"
                    self.right_rotate(k.parent.parent)
            if k == self.root:
                break
        self.root.color = "BLACK"

"""Average Case$O(\log n)$Secara rata-rata, pohon terdistribusi secara seimbang sehingga tinggi pohon adalah $\log n$.Worst Case$O(\log n)$Berbeda dengan Binary Search Tree biasa yang bisa menjadi $O(n)$, aturan pewarnaan RBT menjamin tinggi maksimal pohon tidak lebih dari $2 \log(n+1)$."""