# -*- coding: utf-8 -*-
"""Praktikum1 Muhammad Fadil Juan PamungkasG.211.25.0067.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BQKtP478cSDMbbniB_XE4oIaMWuc4Tlu
"""

def hitung_faktorial(n):
    hasil = 1
    for i in range(1, n + 1):
        hasil *= i
    return hasil
print(f"Hasil dari 7! adalah {hitung_faktorial(7)}")

"""Analisis Time ComplexityDalam analisis algoritma, kita melihat bagaimana waktu eksekusi bertambah seiring bertambahnya nilai input $n$.Time Complexity: $O(n)$Fungsi ini memiliki kompleksitas waktu linear. Mengapa? Karena terdapat satu perulangan (for loop) yang berjalan dari $1$ hingga $n$. Jika $n = 7$, loop berjalan 7 kali. Jika $n = 1.000$, loop berjalan 1.000 kali.Space Complexity: $O(1)$Kompleksitas ruangnya konstan karena kita hanya menggunakan satu variabel penampung (hasil) terlepas dari seberapa besar nilai $n$ yang dimasukkan (dengan asumsi ukuran integer tidak melampaui batas memori)."""